export const CREATE_ARTSTUDIO_REQUEST = "CREATE_ARTSTUDIO_REQUEST";
export const CREATE_ARTSTUDIO_SUCCESS = "CREATE_ARTSTUDIO_SUCCESS";
export const CREATE_ARTSTUDIO_FAILURE = "CREATE_ARTSTUDIO_FAILURE";

export const GET_ALL_ARTSTUDIOS_REQUEST = " GET_ALL_ARTSTUDIO_REQUEST";
export const GET_ALL_ARTSTUDIOS_SUCCESS = " GET_ALL_ARTSTUDIO_SUCCESS";
export const GET_ALL_ARTSTUDIOS_FAILURE = " GET_ALL_ARTSTUDIO_FAILURE";

export const DELETE_ARTSUDIO_REQUEST = "DELETE_ARTSUDIO_REQUEST";
export const DELETE_ARTSUDIO_SUCCESS = "DELETE_ARTSUDIO_SUCCESS";
export const DELETE_ARTSUDIO_FAILURE = "DELETE_ARTSUDIO_FAILURE";

export const UPDATE_ARTSTUDIO_REQUEST = "UPDATE_ARTSTUDIO_REQUEST";
export const UPDATE_ARTSTUDIO_SUCCESS = "UPDATE_ARTSTUDIO_SUCCESS";
export const UPDATE_ARTSTUDIO_FAILURE = "UPDATE_ARTSTUDIO_FAILURE";

export const GET_ARTSTUDIO_BY_ID_REQUEST = "GET_ARTSUDIO_BY_ID_REQUEST";
export const GET_ARTSTUDIO_BY_ID_SUCCESS = "GET_ARTSUDIO_BY_ID_SUCCESS";
export const GET_ARTSTUDIO_BY_ID_FAILURE = "GET_ARTSUDIO_BY_ID_FAILURE";

export const GET_ARTSTUDIO_BY_USER_ID_REQUEST = "GET_ARTSTUDIO_BY_USER_ID_REQUEST";
export const GET_ARTSTUDIO_BY_USER_ID_SUCCESS = "GET_ARTSTUDIO_BY_USER_ID_SUCCESS";
export const GET_ARTSTUDIO_BY_USER_ID_FAILURE = "GET_ARTSTUDIO_BY_USER_ID_FAILURE";

export const UPDATE_ARTSTUDIO_STATUS_REQUEST = "UPDATE_ARTSTUDIO_STATUS_REQUEST";
export const UPDATE_ARTSTUDIO_STATUS_SUCCESS = "UPDATE_ARTSTUDIO_STATUS_SUCCESS";
export const UPDATE_ARTSTUDIO_STATUS_FAILURE = "UPDATE_ARTSTUDIO_STATUS_FAILURE";

export const CREATE_GENRE_REQUEST = "CREATE_GENRE_REQUEST";
export const CREATE_GENRE_SUCCESS = "CREATE_GENRE_SUCCESS";
export const CREATE_GENRE_FAILURE = "CREATE_GENRE_FAILURE";

export const GET_ARTSUDIO_GENRE_REQUEST = "GET_ARTSUDIO_GENRE_REQUEST";
export const GET_ARTSUDIO_GENRE_SUCCESS = "GET_ARTSUDIO_GENRE_SUCCESS";
export const GET_ARTSUDIO_GENRE_FAILURE = "GET_ARTSUDIO_GENRE_FAILURE";
