
export const CREATE_ARTWORK_ITEM_REQUEST = " CREATE_ARTWORK_ITEM_REQUEST";
export const CREATE_ARTWORK_ITEM_SUCCESS = " CREATE_ARTWORK_ITEM_SUCCESS";
export const CREATE_ARTWORK_ITEM_FAILURE = " CREATE_ARTWORK_ITEM_FAILURE";

export const GET_ARTWORKS_BY_ARTSTUDIO_ID_REQUEST = "GET_ARTWORK_BY_ARTSTUDIO_ID_REQUEST";
export const GET_ARTWORKS_BY_ARTSTUDIO_ID_SUCCESS = "GET_ARTWORK_BY_ARTSTUDIO_ID_SUCCESS";
export const GET_ARTWORKS_BY_ARTSTUDIO_ID_FAILURE = "GET_ARTWORK_BY_ARTSTUDIO_ID_FAILURE";

export const DELETE_ARTWORK_REQUEST = "DELETE_ARTWORK_REQUEST";
export const DELETE_ARTWORK_SUCCESS = "DELETE_ARTWORK_SUCCESS";
export const DELETE_ARTWORK_FAILURE = "DELETE_ARTWORK_FAILURE";

export const SEARCH_ARTWORK_REQUEST = "SEARCH_ARTWORK_REQUEST";
export const SEARCH_ARTWORK_SUCCESS = "SEARCH_ARTWORK_SUCESS";
export const SEARCH_ARTWORK_FAILURE = "SEARCH_ARTWORK_FAILURE";

export const UPDATE_ARTWORK_AVAILABILITY_REQUEST = "UPDATE_ARTWORK_AVAILABILITY_REQUEST";
export const UPDATE_ARTWORK_AVAILABILITY_SUCCESS = "UPDATE_ARTWORK_AVAILABILITY_SUCCESS";
export const UPDATE_ARTWORK_AVAILABILITY_FAILURE = "UPDATE_ARTWORK_AVAILABILITY_FAILURE";
